# Every key below is that system's SSH host key, converted from /etc/ssh/ssh_host_ed25519_key.pub with ssh-to-age.
keys:
  - &sparxie_host age1tddj97txq5mckvzrs8czekp5lc530rc35yw0mtd3w9qxjjwf4vpsn7s8yl

creation_rules:
  - path_regex: hosts/sparxie/secrets\.yaml$
    key_groups:
      - age:
          - *sparxie_host
